username: ""
name: ""
domain: ""

serviceKind: "web"    # web api worker

mode: "app"

metallb:
  addressPool: "192.168.1.200-192.168.1.250"

image: 
  repository: "nginx"
  tag: "stable-alpine"
  pullPloicy: "IfNotPresent"

containerPort: 80

resources:
  request:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"

ingress:
  enabled: false
  className: ""
  host: ""
  path: /

service: 
  enabled: true 
  type: "LoadBalancer"
  port: 80