apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.username }}-{{ .Values.name }}
  labels:
    app: {{ .Values.username }}-{{ .Values.name }}
    service-kind: {{ .Values.serviceKind | default "web" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.username }}-{{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.username }}-{{ .Values.name }}
        service-kind: {{ .Values.serviceKind | default "web" }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPloicy | default "IfNotPresent" }}          
          ports:
            - containerPort: {{ .Values.containerPort | default 80 }}
          resources:
            requests:
              cpu: {{ .Values.resources.request.cpu | default "50m" }}
              memory: {{ .Values.resources.request.memory | default "64Mi" }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | default "200m" }}
              memory: {{ .Values.resources.limits.memory | default "128Mi" }}