{{- if and .Values.service.enabled (ne .Values.serviceKind "worker") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.username }}-{{ .Values.name }}
  labels:
    app: {{ .Values.username }}-{{ .Values.name }}
  annotations:
    metallb.io/address-pool: {{ .Values.metallb.addressPool | quote }}
spec:
  type: {{ .Values.service.type | default "LoadBalancer" }}
  selector:
    app: {{ .Values.username }}-{{ .Values.name }}
  ports:
    - name: http
      port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.containerPort | default 80 }}
{{- end }}