apiVersion: v1
kind: Service
metadata:
  name: hello-{{ .Values.username }}-{{ .Values.name }}
  labels:
    app: hello-{{ .Values.username }}-{{ .Values.name }}
  annotations:
    metallb.io/address-pool: {{ .Values.metallb.addressPool | quote }}
spec:
  type: LoadBalancer
  selector:
    app: hello-{{ .Values.username }}-{{ .Values.name }}
  ports:
    - name: http
      port: 80
      targetPort: 80